/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as flashLoanArbitrageSol from "./FlashLoanArbitrage.sol";
export type { flashLoanArbitrageSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as mocks from "./mocks";
export type { mocks };
import type * as security from "./security";
export type { security };
