/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iAaveV3Sol from "./IAaveV3.sol";
export type { iAaveV3Sol };
import type * as idexRouterSol from "./IDEXRouter.sol";
export type { idexRouterSol };
