/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IACLManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "isAssetListingAdmin"
      | "isBridge"
      | "isEmergencyAdmin"
      | "isFlashBorrower"
      | "isPoolAdmin"
      | "isRiskAdmin"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "isAssetListingAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isBridge",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isEmergencyAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isFlashBorrower",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isPoolAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRiskAdmin",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "isAssetListingAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isBridge", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isEmergencyAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isFlashBorrower",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isPoolAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRiskAdmin",
    data: BytesLike
  ): Result;
}

export interface IACLManager extends BaseContract {
  connect(runner?: ContractRunner | null): IACLManager;
  waitForDeployment(): Promise<this>;

  interface: IACLManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  isAssetListingAdmin: TypedContractMethod<
    [admin: AddressLike],
    [boolean],
    "view"
  >;

  isBridge: TypedContractMethod<[bridge: AddressLike], [boolean], "view">;

  isEmergencyAdmin: TypedContractMethod<
    [admin: AddressLike],
    [boolean],
    "view"
  >;

  isFlashBorrower: TypedContractMethod<
    [borrower: AddressLike],
    [boolean],
    "view"
  >;

  isPoolAdmin: TypedContractMethod<[admin: AddressLike], [boolean], "view">;

  isRiskAdmin: TypedContractMethod<[admin: AddressLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "isAssetListingAdmin"
  ): TypedContractMethod<[admin: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isBridge"
  ): TypedContractMethod<[bridge: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isEmergencyAdmin"
  ): TypedContractMethod<[admin: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isFlashBorrower"
  ): TypedContractMethod<[borrower: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isPoolAdmin"
  ): TypedContractMethod<[admin: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isRiskAdmin"
  ): TypedContractMethod<[admin: AddressLike], [boolean], "view">;

  filters: {};
}
