/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace IPoolDataProvider {
  export type TokenDataStruct = { symbol: string; tokenAddress: AddressLike };

  export type TokenDataStructOutput = [symbol: string, tokenAddress: string] & {
    symbol: string;
    tokenAddress: string;
  };
}

export interface IPoolDataProviderInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getAllATokens"
      | "getAllReservesTokens"
      | "getReserveCaps"
      | "getReserveConfigurationData"
      | "getUserReserveData"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getAllATokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllReservesTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getReserveCaps",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getReserveConfigurationData",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserReserveData",
    values: [AddressLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAllATokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllReservesTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReserveCaps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReserveConfigurationData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserReserveData",
    data: BytesLike
  ): Result;
}

export interface IPoolDataProvider extends BaseContract {
  connect(runner?: ContractRunner | null): IPoolDataProvider;
  waitForDeployment(): Promise<this>;

  interface: IPoolDataProviderInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAllATokens: TypedContractMethod<
    [],
    [IPoolDataProvider.TokenDataStructOutput[]],
    "view"
  >;

  getAllReservesTokens: TypedContractMethod<
    [],
    [IPoolDataProvider.TokenDataStructOutput[]],
    "view"
  >;

  getReserveCaps: TypedContractMethod<
    [asset: AddressLike],
    [[bigint, bigint] & { borrowCap: bigint; supplyCap: bigint }],
    "view"
  >;

  getReserveConfigurationData: TypedContractMethod<
    [asset: AddressLike],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        boolean,
        boolean,
        boolean
      ] & {
        decimals: bigint;
        ltv: bigint;
        liquidationThreshold: bigint;
        liquidationBonus: bigint;
        reserveFactor: bigint;
        usageAsCollateralEnabled: boolean;
        borrowingEnabled: boolean;
        stableBorrowRateEnabled: boolean;
        isActive: boolean;
        isFrozen: boolean;
      }
    ],
    "view"
  >;

  getUserReserveData: TypedContractMethod<
    [asset: AddressLike, user: AddressLike],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        currentATokenBalance: bigint;
        currentStableDebt: bigint;
        currentVariableDebt: bigint;
        principalStableDebt: bigint;
        scaledVariableDebt: bigint;
        stableBorrowRate: bigint;
        liquidityRate: bigint;
        stableRateLastUpdated: bigint;
        usageAsCollateralEnabled: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAllATokens"
  ): TypedContractMethod<
    [],
    [IPoolDataProvider.TokenDataStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAllReservesTokens"
  ): TypedContractMethod<
    [],
    [IPoolDataProvider.TokenDataStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReserveCaps"
  ): TypedContractMethod<
    [asset: AddressLike],
    [[bigint, bigint] & { borrowCap: bigint; supplyCap: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReserveConfigurationData"
  ): TypedContractMethod<
    [asset: AddressLike],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        boolean,
        boolean,
        boolean
      ] & {
        decimals: bigint;
        ltv: bigint;
        liquidationThreshold: bigint;
        liquidationBonus: bigint;
        reserveFactor: bigint;
        usageAsCollateralEnabled: boolean;
        borrowingEnabled: boolean;
        stableBorrowRateEnabled: boolean;
        isActive: boolean;
        isFrozen: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserReserveData"
  ): TypedContractMethod<
    [asset: AddressLike, user: AddressLike],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        currentATokenBalance: bigint;
        currentStableDebt: bigint;
        currentVariableDebt: bigint;
        principalStableDebt: bigint;
        scaledVariableDebt: bigint;
        stableBorrowRate: bigint;
        liquidityRate: bigint;
        stableRateLastUpdated: bigint;
        usageAsCollateralEnabled: boolean;
      }
    ],
    "view"
  >;

  filters: {};
}
