/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface ICurveCryptoSwapInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin_fee"
      | "balances"
      | "coins"
      | "exchange"
      | "exchange_underlying"
      | "fee"
      | "future_A_gamma"
      | "get_dy"
      | "get_dy_underlying"
      | "initial_A_gamma"
      | "last_prices"
      | "last_prices_timestamp"
      | "price_oracle"
      | "price_scale"
      | "token"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "admin_fee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "balances",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "coins", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "exchange",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "exchange_underlying",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "fee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "future_A_gamma",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "get_dy",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "get_dy_underlying",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initial_A_gamma",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "last_prices",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "last_prices_timestamp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "price_oracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "price_scale",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;

  decodeFunctionResult(functionFragment: "admin_fee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balances", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "coins", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "exchange", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "exchange_underlying",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "future_A_gamma",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "get_dy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "get_dy_underlying",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initial_A_gamma",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "last_prices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "last_prices_timestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "price_oracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "price_scale",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
}

export interface ICurveCryptoSwap extends BaseContract {
  connect(runner?: ContractRunner | null): ICurveCryptoSwap;
  waitForDeployment(): Promise<this>;

  interface: ICurveCryptoSwapInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin_fee: TypedContractMethod<[], [bigint], "view">;

  balances: TypedContractMethod<[index: BigNumberish], [bigint], "view">;

  coins: TypedContractMethod<[index: BigNumberish], [string], "view">;

  exchange: TypedContractMethod<
    [i: BigNumberish, j: BigNumberish, dx: BigNumberish, min_dy: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  exchange_underlying: TypedContractMethod<
    [i: BigNumberish, j: BigNumberish, dx: BigNumberish, min_dy: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  fee: TypedContractMethod<[], [bigint], "view">;

  future_A_gamma: TypedContractMethod<[], [[bigint, bigint]], "view">;

  get_dy: TypedContractMethod<
    [i: BigNumberish, j: BigNumberish, dx: BigNumberish],
    [bigint],
    "view"
  >;

  get_dy_underlying: TypedContractMethod<
    [i: BigNumberish, j: BigNumberish, dx: BigNumberish],
    [bigint],
    "view"
  >;

  initial_A_gamma: TypedContractMethod<[], [[bigint, bigint]], "view">;

  last_prices: TypedContractMethod<[], [bigint], "view">;

  last_prices_timestamp: TypedContractMethod<[], [bigint], "view">;

  price_oracle: TypedContractMethod<[], [bigint], "view">;

  price_scale: TypedContractMethod<[], [bigint], "view">;

  token: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin_fee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "balances"
  ): TypedContractMethod<[index: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "coins"
  ): TypedContractMethod<[index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "exchange"
  ): TypedContractMethod<
    [i: BigNumberish, j: BigNumberish, dx: BigNumberish, min_dy: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "exchange_underlying"
  ): TypedContractMethod<
    [i: BigNumberish, j: BigNumberish, dx: BigNumberish, min_dy: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "future_A_gamma"
  ): TypedContractMethod<[], [[bigint, bigint]], "view">;
  getFunction(
    nameOrSignature: "get_dy"
  ): TypedContractMethod<
    [i: BigNumberish, j: BigNumberish, dx: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "get_dy_underlying"
  ): TypedContractMethod<
    [i: BigNumberish, j: BigNumberish, dx: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "initial_A_gamma"
  ): TypedContractMethod<[], [[bigint, bigint]], "view">;
  getFunction(
    nameOrSignature: "last_prices"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "last_prices_timestamp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "price_oracle"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "price_scale"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
