/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface ICurveStableSwapInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "A"
      | "A_precise"
      | "add_liquidity"
      | "admin_fee"
      | "balances"
      | "calc_token_amount"
      | "coins"
      | "exchange"
      | "exchange_underlying"
      | "fee"
      | "get_dy"
      | "get_dy_underlying"
      | "get_virtual_price"
      | "remove_liquidity"
      | "remove_liquidity_imbalance"
      | "remove_liquidity_one_coin"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "A", values?: undefined): string;
  encodeFunctionData(functionFragment: "A_precise", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "add_liquidity",
    values: [[BigNumberish, BigNumberish, BigNumberish], BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "admin_fee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "balances",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calc_token_amount",
    values: [[BigNumberish, BigNumberish, BigNumberish], boolean]
  ): string;
  encodeFunctionData(functionFragment: "coins", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "exchange",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "exchange_underlying",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "fee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "get_dy",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "get_dy_underlying",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "get_virtual_price",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "remove_liquidity",
    values: [BigNumberish, [BigNumberish, BigNumberish, BigNumberish]]
  ): string;
  encodeFunctionData(
    functionFragment: "remove_liquidity_imbalance",
    values: [[BigNumberish, BigNumberish, BigNumberish], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "remove_liquidity_one_coin",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "A", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "A_precise", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "add_liquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin_fee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balances", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calc_token_amount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "coins", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "exchange", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "exchange_underlying",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "get_dy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "get_dy_underlying",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "get_virtual_price",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "remove_liquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "remove_liquidity_imbalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "remove_liquidity_one_coin",
    data: BytesLike
  ): Result;
}

export interface ICurveStableSwap extends BaseContract {
  connect(runner?: ContractRunner | null): ICurveStableSwap;
  waitForDeployment(): Promise<this>;

  interface: ICurveStableSwapInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  A: TypedContractMethod<[], [bigint], "view">;

  A_precise: TypedContractMethod<[], [bigint], "view">;

  add_liquidity: TypedContractMethod<
    [
      amounts: [BigNumberish, BigNumberish, BigNumberish],
      min_mint_amount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  admin_fee: TypedContractMethod<[], [bigint], "view">;

  balances: TypedContractMethod<[index: BigNumberish], [bigint], "view">;

  calc_token_amount: TypedContractMethod<
    [amounts: [BigNumberish, BigNumberish, BigNumberish], is_deposit: boolean],
    [bigint],
    "view"
  >;

  coins: TypedContractMethod<[index: BigNumberish], [string], "view">;

  exchange: TypedContractMethod<
    [i: BigNumberish, j: BigNumberish, dx: BigNumberish, min_dy: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  exchange_underlying: TypedContractMethod<
    [i: BigNumberish, j: BigNumberish, dx: BigNumberish, min_dy: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  fee: TypedContractMethod<[], [bigint], "view">;

  get_dy: TypedContractMethod<
    [i: BigNumberish, j: BigNumberish, dx: BigNumberish],
    [bigint],
    "view"
  >;

  get_dy_underlying: TypedContractMethod<
    [i: BigNumberish, j: BigNumberish, dx: BigNumberish],
    [bigint],
    "view"
  >;

  get_virtual_price: TypedContractMethod<[], [bigint], "view">;

  remove_liquidity: TypedContractMethod<
    [
      _amount: BigNumberish,
      min_amounts: [BigNumberish, BigNumberish, BigNumberish]
    ],
    [[bigint, bigint, bigint]],
    "nonpayable"
  >;

  remove_liquidity_imbalance: TypedContractMethod<
    [
      amounts: [BigNumberish, BigNumberish, BigNumberish],
      max_burn_amount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  remove_liquidity_one_coin: TypedContractMethod<
    [_token_amount: BigNumberish, i: BigNumberish, min_amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(nameOrSignature: "A"): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "A_precise"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "add_liquidity"
  ): TypedContractMethod<
    [
      amounts: [BigNumberish, BigNumberish, BigNumberish],
      min_mint_amount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "admin_fee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "balances"
  ): TypedContractMethod<[index: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "calc_token_amount"
  ): TypedContractMethod<
    [amounts: [BigNumberish, BigNumberish, BigNumberish], is_deposit: boolean],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "coins"
  ): TypedContractMethod<[index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "exchange"
  ): TypedContractMethod<
    [i: BigNumberish, j: BigNumberish, dx: BigNumberish, min_dy: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "exchange_underlying"
  ): TypedContractMethod<
    [i: BigNumberish, j: BigNumberish, dx: BigNumberish, min_dy: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "get_dy"
  ): TypedContractMethod<
    [i: BigNumberish, j: BigNumberish, dx: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "get_dy_underlying"
  ): TypedContractMethod<
    [i: BigNumberish, j: BigNumberish, dx: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "get_virtual_price"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "remove_liquidity"
  ): TypedContractMethod<
    [
      _amount: BigNumberish,
      min_amounts: [BigNumberish, BigNumberish, BigNumberish]
    ],
    [[bigint, bigint, bigint]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "remove_liquidity_imbalance"
  ): TypedContractMethod<
    [
      amounts: [BigNumberish, BigNumberish, BigNumberish],
      max_burn_amount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "remove_liquidity_one_coin"
  ): TypedContractMethod<
    [_token_amount: BigNumberish, i: BigNumberish, min_amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  filters: {};
}
