/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface ICurveRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "get_balances"
      | "get_coins"
      | "get_exchange_amount"
      | "get_lp_token"
      | "get_n_coins"
      | "get_pool_from_lp_token"
      | "get_underlying_coins"
      | "pool_count"
      | "pool_list"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "get_balances",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "get_coins",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "get_exchange_amount",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "get_lp_token",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "get_n_coins",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "get_pool_from_lp_token",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "get_underlying_coins",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "pool_count",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pool_list",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "get_balances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "get_coins", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "get_exchange_amount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "get_lp_token",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "get_n_coins",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "get_pool_from_lp_token",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "get_underlying_coins",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pool_count", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pool_list", data: BytesLike): Result;
}

export interface ICurveRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ICurveRegistry;
  waitForDeployment(): Promise<this>;

  interface: ICurveRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  get_balances: TypedContractMethod<[pool: AddressLike], [bigint[]], "view">;

  get_coins: TypedContractMethod<[pool: AddressLike], [string[]], "view">;

  get_exchange_amount: TypedContractMethod<
    [
      pool: AddressLike,
      from: AddressLike,
      to: AddressLike,
      amount: BigNumberish
    ],
    [bigint],
    "view"
  >;

  get_lp_token: TypedContractMethod<[pool: AddressLike], [string], "view">;

  get_n_coins: TypedContractMethod<
    [pool: AddressLike],
    [[bigint, bigint]],
    "view"
  >;

  get_pool_from_lp_token: TypedContractMethod<
    [lp_token: AddressLike],
    [string],
    "view"
  >;

  get_underlying_coins: TypedContractMethod<
    [pool: AddressLike],
    [string[]],
    "view"
  >;

  pool_count: TypedContractMethod<[], [bigint], "view">;

  pool_list: TypedContractMethod<[i: BigNumberish], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "get_balances"
  ): TypedContractMethod<[pool: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "get_coins"
  ): TypedContractMethod<[pool: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "get_exchange_amount"
  ): TypedContractMethod<
    [
      pool: AddressLike,
      from: AddressLike,
      to: AddressLike,
      amount: BigNumberish
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "get_lp_token"
  ): TypedContractMethod<[pool: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "get_n_coins"
  ): TypedContractMethod<[pool: AddressLike], [[bigint, bigint]], "view">;
  getFunction(
    nameOrSignature: "get_pool_from_lp_token"
  ): TypedContractMethod<[lp_token: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "get_underlying_coins"
  ): TypedContractMethod<[pool: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "pool_count"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pool_list"
  ): TypedContractMethod<[i: BigNumberish], [string], "view">;

  filters: {};
}
