/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  AddressLike,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  MaliciousReentrancy,
  MaliciousReentrancyInterface,
} from "../../../contracts/mocks/MaliciousReentrancy";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_target",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    stateMutability: "payable",
    type: "fallback",
  },
  {
    inputs: [],
    name: "attemptReentrancy",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60806040526000805460ff60a01b1916905534801561001d57600080fd5b506040516102c13803806102c183398101604081905261003c91610061565b600080546001600160a01b0319166001600160a01b0392909216919091179055610091565b60006020828403121561007357600080fd5b81516001600160a01b038116811461008a57600080fd5b9392505050565b610221806100a06000396000f3fe60806040526004361061001e5760003560e01c8063bc8cf3dd146100bd575b600054600160a01b900460ff16156100bb576000805460408051600481526024810182526020810180516001600160e01b0316638456cb5960e01b17905290516001600160a01b039092169161007491906101bc565b6000604051808303816000865af19150503d80600081146100b1576040519150601f19603f3d011682016040523d82523d6000602084013e6100b6565b606091505b505050505b005b3480156100c957600080fd5b506100bb6000805460ff60a01b198116600160a01b17825560408051600481526024810182526020810180516001600160e01b0316638456cb5960e01b17905290516001600160a01b039092169161012191906101bc565b6000604051808303816000865af19150503d806000811461015e576040519150601f19603f3d011682016040523d82523d6000602084013e610163565b606091505b5050905080156101b95760405162461bcd60e51b815260206004820152601e60248201527f5265656e7472616e63792073686f756c642062652070726576656e7465640000604482015260640160405180910390fd5b50565b6000825160005b818110156101dd57602081860181015185830152016101c3565b50600092019182525091905056fea264697066735822122068ce5c6a3ebfa5ace86af2ec7ef68032487a2efbccc34c2ada14b37638d7852864736f6c63430008140033";

type MaliciousReentrancyConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MaliciousReentrancyConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MaliciousReentrancy__factory extends ContractFactory {
  constructor(...args: MaliciousReentrancyConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    _target: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(_target, overrides || {});
  }
  override deploy(
    _target: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(_target, overrides || {}) as Promise<
      MaliciousReentrancy & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): MaliciousReentrancy__factory {
    return super.connect(runner) as MaliciousReentrancy__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MaliciousReentrancyInterface {
    return new Interface(_abi) as MaliciousReentrancyInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MaliciousReentrancy {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as MaliciousReentrancy;
  }
}
